import streamlit as st
import pandas as pd
import plotly.express as px
from io import BytesIO
import tempfile
import os

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Table, TableStyle,
    Spacer, PageBreak
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm

from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF

from csv_engine import process_csv

# ================= CONFIG =================
st.set_page_config(page_title="R E D R O C K", layout="wide")
st.title("🟥 R E D R O C K")
st.caption("Data inspection • filtros • métricas • agrupaciones • gráficos")

# ================= STATE =================
if "filters" not in st.session_state:
    st.session_state.filters = []

# ================= SIDEBAR =================
st.sidebar.header("Configuración")
uploaded_file = st.sidebar.file_uploader("Cargar archivo CSV", type=["csv"])

if not uploaded_file:
    st.info("👈 Carga un archivo CSV para comenzar")
    st.stop()

temp_path = "temp_uploaded.csv"
with open(temp_path, "wb") as f:
    f.write(uploaded_file.getbuffer())

# ================= PROCESS =================
with st.spinner("Procesando datos..."):
    preview_df, df_original = process_csv(temp_path, st.session_state.filters)

# ================= COLUMN SELECTION =================
st.sidebar.subheader("Columnas a mostrar")
selected_columns = st.sidebar.multiselect(
    "Selecciona las columnas visibles",
    df_original.columns.tolist(),
    default=df_original.columns.tolist()
)

df_display = df_original[selected_columns].copy()

# ================= FILTERS =================
st.sidebar.subheader("Filtros")
with st.sidebar.expander("➕ Agregar filtro"):
    f_col = st.selectbox("Columna", df_original.columns)
    f_op = st.selectbox("Operador", ["=", "!=", ">", "<", ">=", "<=", "contiene"])
    f_val = st.text_input("Valor")
    if st.button("Agregar filtro"):
        st.session_state.filters.append((f_col, f_op, f_val))
        st.rerun()

if st.session_state.filters:
    st.sidebar.markdown("### Filtros activos")
    for i, f in enumerate(st.session_state.filters):
        col1, col2 = st.sidebar.columns([4, 1])
        col1.write(f"{i+1}. {f[0]} {f[1]} {f[2]}")
        if col2.button("✕", key=f"del_{i}"):
            st.session_state.filters.pop(i)
            st.rerun()

# ================= ANÁLISIS =================
st.sidebar.subheader("Análisis")

group_col = st.sidebar.selectbox(
    "Agrupar por",
    ["— Ninguno —"] + df_original.columns.tolist()
)

metric_col = st.sidebar.selectbox(
    "Columna métrica",
    df_original.columns
)

metric_op_label = st.sidebar.selectbox(
    "Operación",
    ["Conteo", "Suma", "Promedio", "Mínimo", "Máximo"]
)

agg_map = {
    "Conteo": "count",
    "Suma": "sum",
    "Promedio": "mean",
    "Mínimo": "min",
    "Máximo": "max"
}
agg_func = agg_map[metric_op_label]

# ================= CÁLCULOS =================
df_calc = df_display.copy()
grouped_df = None
metric_value = None

if group_col != "— Ninguno —":
    grouped_df = (
        df_calc
        .groupby(group_col, observed=True)[metric_col]
        .agg(agg_func)
        .reset_index()
        .rename(columns={metric_col: metric_op_label})
        .sort_values(by=metric_op_label, ascending=False)
    )
else:
    s = df_calc[metric_col]
    if metric_op_label == "Conteo":
        metric_value = len(s)
    elif metric_op_label == "Suma":
        metric_value = s.sum()
    elif metric_op_label == "Promedio":
        metric_value = s.mean()
    elif metric_op_label == "Mínimo":
        metric_value = s.min()
    elif metric_op_label == "Máximo":
        metric_value = s.max()

# ================= VISUAL =================
st.subheader("Resultado")

if grouped_df is not None:
    st.dataframe(grouped_df, use_container_width=True)
else:
    st.metric(metric_op_label, metric_value)

# ================= GRÁFICO =================
st.subheader("Gráfico")

fig = None
if grouped_df is not None and not grouped_df.empty:
    fig = px.bar(
        grouped_df,
        x=group_col,
        y=metric_op_label,
        title=f"{metric_op_label} por {group_col}",
        color_discrete_sequence=["#FF0000"]
    )
    st.plotly_chart(fig, use_container_width=True)

# ================= PDF =================
def footer(canvas, doc):
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.grey)
    canvas.drawCentredString(A4[0] / 2, 1.5 * cm, "Generated by RedRock 2026")

def plot_to_svg():
    if fig is None:
        return None
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".svg")
    fig.write_image(tmp.name, format="svg")
    tmp.close()
    return tmp.name

def df_to_table(data_df, title):
    styles = getSampleStyleSheet()
    elements = [Paragraph(title, styles["Heading2"]), Spacer(1, 12)]
    data = [data_df.columns.tolist()] + data_df.values.tolist()
    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.black),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
    ]))
    elements.append(table)
    elements.append(PageBreak())
    return elements

def generate_pdf():
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("R E D R O C K – Reporte de Datos", styles["Title"]))
    elements.append(Spacer(1, 20))

    svg_path = plot_to_svg()
    if svg_path:
        drawing = svg2rlg(svg_path)
        elements.append(Paragraph("Análisis Gráfico", styles["Heading2"]))
        elements.append(drawing)
        elements.append(PageBreak())
        os.unlink(svg_path)

    if grouped_df is not None:
        elements += df_to_table(grouped_df, "Resultados Agrupados")

    doc.build(elements, onFirstPage=footer, onLaterPages=footer)
    buffer.seek(0)
    return buffer

if st.button("⬇ Exportar PDF profesional"):
    pdf = generate_pdf()
    st.download_button(
        "Descargar PDF",
        pdf,
        "redrock_reporte.pdf",
        mime="application/pdf"
    )

# ================= CLEANUP =================
if os.path.exists(temp_path):
    os.remove(temp_path)

